### PR TITLE
ARROW-2768: Support Ubuntu 18.04

### PR DESCRIPTION
**Pull request by yahonda**
This pull request provides Ubuntu 18.04 support.

### CODE REVIEW

**Comment by yahonda** [comment]
cc @kou who suggested to open a pull request and a JIRA ticket.

**Review by kou — APPROVED** [review]
Thanks!
I've added Ubuntu 18.04 to build list on Travis CI. I'll merge this when the build is succeeded.

**Comment by kou** [comment]
Umm. Parallel build may cause build failure.

**Comment by kou** [comment]
I've disabled parallel build. If it works well, I'll merge this.

**Comment by kou** [comment]
It works well. I've merged.

**Comment by yahonda** [comment]
Thanks for the follow-up and merging.

**Comment by kou** [comment]
I've uploaded packages for Ubuntu 18.04 to packages.red-data-tools.org.
Keep up the good work!

**Pull request merged**
