### PR TITLE
ARROW-1269: Windows build scripts for creating pyarrow wheels and uploading to BinTray

### PR DESCRIPTION
**Pull request by wesm**
We will want to configure a central staging location for package artifacts

### CODE REVIEW

**Review by xhochy — APPROVED** [review]
+1 merge after Appveyor was setup by INFRA

**Comment by xhochy** [comment]
@wesm note that you should merge this PR via the github UI and not via any script.

**Comment by wesm** [comment]
https://issues.apache.org/jira/browse/INFRA-14722

**Comment by wesm** [comment]
Appveyor is on, will merge once the build passes. We'll need to configure things so that PRs don't upload artifacts

**Comment by wesm** [comment]
Ah, this is failing because of ARROW-1275.

**Pull request merged**
