### PR TITLE
Update Linux package versions to 0.7.0

### PR DESCRIPTION
**Pull request by wesm**
@kou does anything else need to be changed to build these packages? We can upload them to apache/arrow bintray once they are built

### CODE REVIEW

**Comment by kou** [comment]
We also need to add new version entry to `cpp-linux/debian/changelog` and `cpp-linux/yum/arrow.spec.in`.
We can do it by running `rake version:update` in `cpp-linux/` directory.

If you fail to run the command, I can run it and provide a patch.

**Comment by wesm** [comment]
I'll give it a shot and let you know if I have problems

**Comment by kou** [comment]
+1

But build for CentOS 6 fails with the following message:

```text
BFD: /root/rpmbuild/BUILDROOT/arrow-0.7.0-1.el6.x86_64/usr/lib64/libarrow.a(compression_zstd.cc.o): invalid relocation type 42
```

It may be binutils related problems. I'll look into this after RubyKaigi 2017 is finished.

**Comment by wesm** [comment]
OK, I will merge for now and let you look into it

**Comment by kou** [comment]
OK.

**Pull request merged**
