### PR TITLE
Update descriptor.json by "rake version:update"

### PR DESCRIPTION
**Pull request by kou**
It's just for easy to maintain.

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1

**Comment by kou** [comment]
I want to merge this change by myself.
Can you give me write access to the repository?

**Comment by wesm** [comment]
I will have to ask INFRA about this, I'm not sure how I got write access here to begin with

**Comment by wesm** [comment]
https://issues.apache.org/jira/browse/INFRA-15163

**Comment by kou** [comment]
Thanks!

**Pull request merged**
