### PR TITLE
Build 0.8.0 wheels

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by wesm** [comment]
Most strange, perhaps @matthew-brett could advise on the macOS failures?

**Comment by kou** [comment]
I'll put a patch to fix deb/rpm package builds later.
It's OK to me that this change is merged my patch because I can put my change after this change is merged.

**Comment by matthew-brett** [comment]
I wonder if you're hitting https://github.com/travis-ci/travis-ci/issues/8703#issuecomment-348866918 ?

**Comment by xhochy** [comment]
@matthew-brett Awesome, that was the problem! Wheels now build.

**Comment by xhochy** [comment]
Merging as all builds except the APT/YUM packages passed.

**Comment by BryanCutler** [comment]
Thanks for fixing this @xhochy!  I uploaded the macOS wheels for pip after this update

**Pull request merged**
